name: Android Build (ZIP)

on:
  push:
    branches:
      - main
  workflow_dispatch: # ম্যানুয়ালি চালানোর অপশন

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify ZIP exists
        run: ls -l

      - name: Unzip project
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          unzip -o "*.zip" -d .
          echo "------ Root directory after unzip ------"
          ls -l
          echo "------ app directory ------"
          ls -l app || true
          echo "------ gradle directory ------"
          ls -l gradle || true

      - name: Fail if gradlew missing
        run: |
          if [ ! -f "./gradlew" ]; then
            echo "gradlew NOT FOUND in root! Failing..."
            exit 1
          fi
          echo "gradlew found!"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Debug APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MahamayaCalculator-APK
          path: app/build/outputs/apk/debug/app-debug.apk
